import './styles/globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css"/>
      </head>
      <body>{children}</body>
    </html>
  )
}
